In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("data/Raw/Luxury_Housing_Bangalore.csv")

In [4]:
df.shape

(101000, 18)

In [5]:
df.describe()

,Unit_Size_Sqft,Connectivity_Score,Amenity_Score,Locality_Infra_Score,Avg_Traffic_Time_Min
count,90954.000000,101000.000000,90910.000000,101000.000000,101000.000000
mean,5972.274765,6.992619,7.503663,7.498426,67.182921
std,1783.397836,1.731757,1.440758,1.443128,30.271611
min,-1.000000,4.000031,5.000224,5.000013,15.000000
25%,4477.250000,5.494526,6.260329,6.247954,41.000000
50%,5990.000000,6.985805,7.499123,7.495614,67.000000
75%,7497.000000,8.490000,8.752207,8.749824,93.000000
max,8999.000000,9.999970,9.999865,9.999956,119.000000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101000 entries, 0 to 100999
Data columns (total 18 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           101000 non-null  object
 1   Micro_Market          101000 non-null  object
 2   Project_Name          101000 non-null  object
 3   Developer_Name        101000 non-null  object
 4   Unit_Size_Sqft        90954 non-null   float64
 5   Configuration         101000 non-null  object
 6   Ticket_Price_Cr       90981 non-null   object
 7   Transaction_Type      101000 non-null  object
 8   Buyer_Type            101000 non-null  object
 9   Purchase_Quarter      101000 non-null  object
 10  Connectivity_Score    101000 non-null  float64
 11  Amenity_Score         90910 non-null   float64
 12  Possession_Status     101000 non-null  object
 13  Sales_Channel         101000 non-null  object
 14  NRI_Buyer             101000 non-null  object
 15  Locality_Infra_Score  101000 non-null  float64
 16  Avg_Traffic_Time_Min  101000 non-null  int64
 17  Buyer_Comments        82713 non-null   object
dtypes: float64(4), int64(1), object(13)
memory usage: 13.9+ MB

In [7]:
df.head(10)

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,PROP000001,Sarjapur Road,Project_0,RMZ,4025.0,4bhk,12.750846039118798,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.292151871065954,Primary,Other,2024-06-30,4.839024,NaN,Under construction,NRI Desk,no,7.723898,106,NaN
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4bhk,10.517724412961911,Primary,HNI,2023-12-31,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.
3,PROP000004,bellary road,Project_3,Embassy,6192.0,3BHK,9.396367494232896,Primary,HNI,2024-03-31,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!
4,PROP000005,Koramangala,Project_4,SNN Raj,7147.0,4Bhk,15.345392444511946,Secondary,HNI,2024-12-31,4.525216,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.
5,PROP000006,YELAHANKA,Project_5,Brigade,4290.0,4bhk,₹9.82 Cr,Secondary,HNI,2023-09-30,7.936068,NaN,Launch,Online,no,5.154027,16,Underpriced for location.
6,PROP000007,Bannerghatta Road,Project_6,Prestige,6776.0,5BHK+,10.896752354445224,Secondary,Other,2025-03-31,8.643117,8.355238,Under construction,Direct,no,9.791550,74,Too far from my office.
7,PROP000008,whitefield,Project_7,Total Environment,5763.0,3BHK,9.357538943683888,Secondary,NRI,2025-03-31,6.781306,9.565013,Under construction,Direct,yes,9.054713,31,NaN
8,PROP000009,sarjapur road,Project_8,Prestige,5815.0,3Bhk,12.299449409872416,Secondary,Other,2024-03-31,7.284164,5.580442,Under construction,NRI Desk,yes,8.552046,68,NaN
9,PROP000010,JP NAGAR,Project_9,Puravankara,8675.0,4Bhk,9.193310278863123,Primary,CXO,2023-09-30,9.964399,7.759907,Launch,Direct,yes,8.395691,18,Too far from my office.

In [8]:
df.dtypes

Property_ID              object
Micro_Market             object
Project_Name             object
Developer_Name           object
Unit_Size_Sqft          float64
Configuration            object
Ticket_Price_Cr          object
Transaction_Type         object
Buyer_Type               object
Purchase_Quarter         object
Connectivity_Score      float64
Amenity_Score           float64
Possession_Status        object
Sales_Channel            object
NRI_Buyer                object
Locality_Infra_Score    float64
Avg_Traffic_Time_Min      int64
Buyer_Comments           object
dtype: object

In [9]:
df["Ticket_Price_Cr"]=df["Ticket_Price_Cr"].str.replace('₹','')
df["Ticket_Price_Cr"]=df["Ticket_Price_Cr"].str.replace('Cr','')
df["Ticket_Price_Cr"]=df["Ticket_Price_Cr"].str.replace(' ','')
df.head(10)

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,PROP000001,Sarjapur Road,Project_0,RMZ,4025.0,4bhk,12.750846039118798,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.292151871065954,Primary,Other,2024-06-30,4.839024,NaN,Under construction,NRI Desk,no,7.723898,106,NaN
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4bhk,10.517724412961911,Primary,HNI,2023-12-31,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.
3,PROP000004,bellary road,Project_3,Embassy,6192.0,3BHK,9.396367494232896,Primary,HNI,2024-03-31,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!
4,PROP000005,Koramangala,Project_4,SNN Raj,7147.0,4Bhk,15.345392444511946,Secondary,HNI,2024-12-31,4.525216,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.
5,PROP000006,YELAHANKA,Project_5,Brigade,4290.0,4bhk,9.82,Secondary,HNI,2023-09-30,7.936068,NaN,Launch,Online,no,5.154027,16,Underpriced for location.
6,PROP000007,Bannerghatta Road,Project_6,Prestige,6776.0,5BHK+,10.896752354445224,Secondary,Other,2025-03-31,8.643117,8.355238,Under construction,Direct,no,9.791550,74,Too far from my office.
7,PROP000008,whitefield,Project_7,Total Environment,5763.0,3BHK,9.357538943683888,Secondary,NRI,2025-03-31,6.781306,9.565013,Under construction,Direct,yes,9.054713,31,NaN
8,PROP000009,sarjapur road,Project_8,Prestige,5815.0,3Bhk,12.299449409872416,Secondary,Other,2024-03-31,7.284164,5.580442,Under construction,NRI Desk,yes,8.552046,68,NaN
9,PROP000010,JP NAGAR,Project_9,Puravankara,8675.0,4Bhk,9.193310278863123,Primary,CXO,2023-09-30,9.964399,7.759907,Launch,Direct,yes,8.395691,18,Too far from my office.

In [10]:
df["Purchase_Quarter"]=pd.to_datetime(df["Purchase_Quarter"])

In [11]:
df

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,PROP000001,Sarjapur Road,Project_0,RMZ,4025.0,4bhk,12.750846039118798,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.292151871065954,Primary,Other,2024-06-30,4.839024,NaN,Under construction,NRI Desk,no,7.723898,106,NaN
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4bhk,10.517724412961911,Primary,HNI,2023-12-31,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.
3,PROP000004,bellary road,Project_3,Embassy,6192.0,3BHK,9.396367494232896,Primary,HNI,2024-03-31,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!
4,PROP000005,Koramangala,Project_4,SNN Raj,7147.0,4Bhk,15.345392444511946,Secondary,HNI,2024-12-31,4.525216,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100995,PROP004730,BELLARY ROAD,Project_229,Embassy,8546.0,5Bhk+,11.33081004147843,Secondary,CXO,2024-12-31,8.552797,6.221131,Under construction,NRI Desk,no,7.511827,22,Will buy after possession.
100996,PROP059810,Bellary Road,Project_309,Brigade,3408.0,3bhk,10.829373158307602,Primary,CXO,2024-09-30,6.879269,9.783611,Ready to move,Direct,no,9.851849,26,Agent was not responsive.
100997,PROP065099,HENNUR ROAD,Project_98,RMZ,4691.0,4BHK,11.183303152058548,Primary,NRI,2023-12-31,6.753812,8.383013,Under construction,Broker,no,9.101604,44,Loved the amenities!
100998,PROP093022,rajajinagar,Project_21,Embassy,7435.0,3BHK,10.914156376035923,Secondary,Other,2024-06-30,4.437787,5.756247,Under construction,Broker,yes,8.588551,66,Excellent location!
100999,PROP023826,whitefield,Project_325,L&T Realty,3218.0,4bhk,13.27,Primary,Startup Founder,2023-12-31,7.760416,9.989290,Under construction,Direct,yes,9.917647,58,Loved the amenities!

In [12]:
df.dtypes

Property_ID                     object
Micro_Market                    object
Project_Name                    object
Developer_Name                  object
Unit_Size_Sqft                 float64
Configuration                   object
Ticket_Price_Cr                 object
Transaction_Type                object
Buyer_Type                      object
Purchase_Quarter        datetime64[ns]
Connectivity_Score             float64
Amenity_Score                  float64
Possession_Status               object
Sales_Channel                   object
NRI_Buyer                       object
Locality_Infra_Score           float64
Avg_Traffic_Time_Min             int64
Buyer_Comments                  object
dtype: object

In [13]:
df["Ticket_Price_Cr"]=pd.to_numeric(df["Ticket_Price_Cr"],errors='coerce')

In [14]:
df["Ticket_Price_Cr"]=df["Ticket_Price_Cr"].round(2)

In [15]:
df

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,PROP000001,Sarjapur Road,Project_0,RMZ,4025.0,4bhk,12.75,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.29,Primary,Other,2024-06-30,4.839024,NaN,Under construction,NRI Desk,no,7.723898,106,NaN
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4bhk,10.52,Primary,HNI,2023-12-31,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.
3,PROP000004,bellary road,Project_3,Embassy,6192.0,3BHK,9.40,Primary,HNI,2024-03-31,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!
4,PROP000005,Koramangala,Project_4,SNN Raj,7147.0,4Bhk,15.35,Secondary,HNI,2024-12-31,4.525216,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100995,PROP004730,BELLARY ROAD,Project_229,Embassy,8546.0,5Bhk+,11.33,Secondary,CXO,2024-12-31,8.552797,6.221131,Under construction,NRI Desk,no,7.511827,22,Will buy after possession.
100996,PROP059810,Bellary Road,Project_309,Brigade,3408.0,3bhk,10.83,Primary,CXO,2024-09-30,6.879269,9.783611,Ready to move,Direct,no,9.851849,26,Agent was not responsive.
100997,PROP065099,HENNUR ROAD,Project_98,RMZ,4691.0,4BHK,11.18,Primary,NRI,2023-12-31,6.753812,8.383013,Under construction,Broker,no,9.101604,44,Loved the amenities!
100998,PROP093022,rajajinagar,Project_21,Embassy,7435.0,3BHK,10.91,Secondary,Other,2024-06-30,4.437787,5.756247,Under construction,Broker,yes,8.588551,66,Excellent location!
100999,PROP023826,whitefield,Project_325,L&T Realty,3218.0,4bhk,13.27,Primary,Startup Founder,2023-12-31,7.760416,9.989290,Under construction,Direct,yes,9.917647,58,Loved the amenities!

In [16]:
df["Micro_Market"]=df["Micro_Market"].str.title()

In [17]:
df

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,PROP000001,Sarjapur Road,Project_0,RMZ,4025.0,4bhk,12.75,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.29,Primary,Other,2024-06-30,4.839024,NaN,Under construction,NRI Desk,no,7.723898,106,NaN
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4bhk,10.52,Primary,HNI,2023-12-31,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.
3,PROP000004,Bellary Road,Project_3,Embassy,6192.0,3BHK,9.40,Primary,HNI,2024-03-31,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!
4,PROP000005,Koramangala,Project_4,SNN Raj,7147.0,4Bhk,15.35,Secondary,HNI,2024-12-31,4.525216,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100995,PROP004730,Bellary Road,Project_229,Embassy,8546.0,5Bhk+,11.33,Secondary,CXO,2024-12-31,8.552797,6.221131,Under construction,NRI Desk,no,7.511827,22,Will buy after possession.
100996,PROP059810,Bellary Road,Project_309,Brigade,3408.0,3bhk,10.83,Primary,CXO,2024-09-30,6.879269,9.783611,Ready to move,Direct,no,9.851849,26,Agent was not responsive.
100997,PROP065099,Hennur Road,Project_98,RMZ,4691.0,4BHK,11.18,Primary,NRI,2023-12-31,6.753812,8.383013,Under construction,Broker,no,9.101604,44,Loved the amenities!
100998,PROP093022,Rajajinagar,Project_21,Embassy,7435.0,3BHK,10.91,Secondary,Other,2024-06-30,4.437787,5.756247,Under construction,Broker,yes,8.588551,66,Excellent location!
100999,PROP023826,Whitefield,Project_325,L&T Realty,3218.0,4bhk,13.27,Primary,Startup Founder,2023-12-31,7.760416,9.989290,Under construction,Direct,yes,9.917647,58,Loved the amenities!

In [18]:
df.duplicated().sum()

np.int64(1000)

In [19]:
df.drop_duplicates(inplace=True)

In [20]:
df.duplicated().sum()

np.int64(0)

In [21]:
df.sample(10)

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
68816,PROP068817,Electronic City,Project_316,RMZ,NaN,4bhk,11.73,Primary,CXO,2024-12-31,5.496607,8.573094,Under construction,Online,yes,5.037138,82,Loved the amenities!
25828,PROP025829,Hennur Road,Project_328,Brigade,6953.0,3bhk,8.75,Secondary,HNI,2023-12-31,9.942398,7.217414,Launch,NRI Desk,yes,6.725824,46,Will buy after possession.
12105,PROP012106,Bannerghatta Road,Project_105,Godrej,4243.0,3BHK,NaN,Primary,CXO,2025-03-31,7.519918,6.869386,Ready to move,NRI Desk,yes,5.299832,80,Will buy after possession.
28039,PROP028040,Domlur,Project_39,Godrej,3614.0,3Bhk,12.55,Primary,Other,2024-06-30,6.650308,9.372776,Ready to move,Direct,yes,8.723850,118,NaN
47055,PROP047056,Jayanagar,Project_55,Sobha,6337.0,3BHK,4.83,Primary,NRI,2023-12-31,9.220645,5.387022,Launch,Broker,yes,7.600347,43,Too far from my office.
24163,PROP024164,Hebbal,Project_163,Total Environment,6949.0,5bhk+,11.97,Primary,HNI,2023-12-31,6.911574,7.523336,Launch,Online,no,5.929568,99,Underpriced for location.
12590,PROP012591,Kanakapura Road,Project_90,Sobha,3885.0,4bhk,7.75,Secondary,Other,2024-06-30,7.991779,9.325624,Under construction,Online,no,8.922828,45,Underpriced for location.
82751,PROP082752,Electronic City,Project_251,SNN Raj,4176.0,5Bhk+,8.91,Primary,HNI,2024-03-31,4.018955,6.126097,Ready to move,Direct,yes,9.089140,108,Agent was not responsive.
77313,PROP077314,Rajajinagar,Project_313,Puravankara,5749.0,5BHK+,7.70,Secondary,NRI,2025-03-31,6.832376,5.140696,Ready to move,Broker,no,9.528152,56,Agent was not responsive.
34189,PROP034190,Kanakapura Road,Project_189,SNN Raj,NaN,5Bhk+,NaN,Primary,Startup Founder,2025-03-31,9.192511,6.518706,Ready to move,NRI Desk,yes,8.892496,113,Loved the amenities!

In [22]:
df.isnull().sum()

Property_ID                 0
Micro_Market                0
Project_Name                0
Developer_Name              0
Unit_Size_Sqft           9957
Configuration               0
Ticket_Price_Cr          9913
Transaction_Type            0
Buyer_Type                  0
Purchase_Quarter            0
Connectivity_Score          0
Amenity_Score           10000
Possession_Status           0
Sales_Channel               0
NRI_Buyer                   0
Locality_Infra_Score        0
Avg_Traffic_Time_Min        0
Buyer_Comments          18099
dtype: int64

In [23]:
df["Buyer_Comments"].fillna("No comments",inplace=True)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_25840\420216250.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Buyer_Comments"].fillna("No comments",inplace=True)

In [24]:

df["Amenity_Score"] = pd.to_numeric(df["Amenity_Score"], errors='coerce')
df["Amenity_Score"]=df["Amenity_Score"].fillna(df["Amenity_Score"].median())

In [25]:
df.isnull().sum()

Property_ID                0
Micro_Market               0
Project_Name               0
Developer_Name             0
Unit_Size_Sqft          9957
Configuration              0
Ticket_Price_Cr         9913
Transaction_Type           0
Buyer_Type                 0
Purchase_Quarter           0
Connectivity_Score         0
Amenity_Score              0
Possession_Status          0
Sales_Channel              0
NRI_Buyer                  0
Locality_Infra_Score       0
Avg_Traffic_Time_Min       0
Buyer_Comments             0
dtype: int64

In [26]:
df.loc[df["Unit_Size_Sqft"] <= 0,"Unit_Size_Sqft"]=np.nan
df.loc[df["Ticket_Price_Cr"] <= 0,"Ticket_Price_Cr"]=np.nan

In [27]:
df.describe()

,Unit_Size_Sqft,Ticket_Price_Cr,Purchase_Quarter,Connectivity_Score,Amenity_Score,Locality_Infra_Score,Avg_Traffic_Time_Min
count,89543.000000,90082.000000,100000,100000.000000,100000.000000,100000.000000,100000.000000
mean,6005.393085,12.719790,2024-05-15 06:37:03.072000,6.993001,7.503743,7.499378,67.188020
min,3000.000000,0.660000,2023-06-30 00:00:00,4.000031,5.000224,5.000013,15.000000
25%,4504.000000,10.010000,2023-09-30 00:00:00,5.495535,6.395876,6.249147,41.000000
50%,6004.000000,12.040000,2024-03-31 00:00:00,6.986316,7.499766,7.497347,67.000000
75%,7505.000000,14.100000,2024-09-30 00:00:00,8.490617,8.615671,8.751793,93.000000
max,8999.000000,100.000000,2025-03-31 00:00:00,9.999970,9.999865,9.999956,119.000000
std,1731.276595,7.669958,NaN,1.731699,1.366641,1.443286,30.267763

In [28]:
df.isnull().sum()

Property_ID                 0
Micro_Market                0
Project_Name                0
Developer_Name              0
Unit_Size_Sqft          10457
Configuration               0
Ticket_Price_Cr          9918
Transaction_Type            0
Buyer_Type                  0
Purchase_Quarter            0
Connectivity_Score          0
Amenity_Score               0
Possession_Status           0
Sales_Channel               0
NRI_Buyer                   0
Locality_Infra_Score        0
Avg_Traffic_Time_Min        0
Buyer_Comments              0
dtype: int64

In [29]:
df["Ticket_Price_Cr"]=df["Ticket_Price_Cr"].fillna(df["Ticket_Price_Cr"].median())

In [30]:
df["Unit_Size_Sqft"]=df["Unit_Size_Sqft"].fillna(df["Unit_Size_Sqft"].median())

In [31]:
df["Ticket_Price_Cr"].isna().sum()

np.int64(0)

In [32]:
df["Developer_Name"]=df["Developer_Name"].str.title()

In [33]:
df

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,PROP000001,Sarjapur Road,Project_0,Rmz,4025.0,4bhk,12.75,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.29,Primary,Other,2024-06-30,4.839024,7.499766,Under construction,NRI Desk,no,7.723898,106,No comments
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4bhk,10.52,Primary,HNI,2023-12-31,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.
3,PROP000004,Bellary Road,Project_3,Embassy,6192.0,3BHK,9.40,Primary,HNI,2024-03-31,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!
4,PROP000005,Koramangala,Project_4,Snn Raj,7147.0,4Bhk,15.35,Secondary,HNI,2024-12-31,4.525216,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,PROP099996,Bellary Road,Project_495,L&T Realty,5550.0,5Bhk+,10.19,Primary,NRI,2023-12-31,8.379908,7.499766,Under construction,Online,yes,8.378800,109,Underpriced for location.
99996,PROP099997,Yelahanka,Project_496,L&T Realty,3171.0,4Bhk,12.27,Secondary,Other,2023-12-31,4.716304,6.374069,Launch,Broker,yes,7.025209,20,Great view from 15th floor.
99997,PROP099998,Rajajinagar,Project_497,Prestige,5599.0,4BHK,13.73,Primary,Startup Founder,2023-09-30,6.193347,7.482473,Launch,NRI Desk,yes,8.984990,63,No comments
99998,PROP099999,Indiranagar,Project_498,Snn Raj,7342.0,4bhk,10.36,Primary,NRI,2024-09-30,9.435646,6.369276,Under construction,NRI Desk,yes,7.634717,89,No comments
99999,PROP100000,Hennur Road,Project_499,Embassy,5016.0,5Bhk+,10.42,Primary,Startup Founder,2024-09-30,5.786292,5.284026,Launch,Broker,yes,6.039943,95,No comments

In [34]:
df.columns

Index(['Property_ID', 'Micro_Market', 'Project_Name', 'Developer_Name',
       'Unit_Size_Sqft', 'Configuration', 'Ticket_Price_Cr',
       'Transaction_Type', 'Buyer_Type', 'Purchase_Quarter',
       'Connectivity_Score', 'Amenity_Score', 'Possession_Status',
       'Sales_Channel', 'NRI_Buyer', 'Locality_Infra_Score',
       'Avg_Traffic_Time_Min', 'Buyer_Comments'],
      dtype='object')

In [35]:
df["Price_Per_Sqft"]=(df["Ticket_Price_Cr"]*10000000/df["Unit_Size_Sqft"]).round()

In [36]:
df

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments,Price_Per_Sqft
0,PROP000001,Sarjapur Road,Project_0,Rmz,4025.0,4bhk,12.75,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!,31677.0
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.29,Primary,Other,2024-06-30,4.839024,7.499766,Under construction,NRI Desk,no,7.723898,106,No comments,28281.0
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4bhk,10.52,Primary,HNI,2023-12-31,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.,13650.0
3,PROP000004,Bellary Road,Project_3,Embassy,6192.0,3BHK,9.40,Primary,HNI,2024-03-31,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!,15181.0
4,PROP000005,Koramangala,Project_4,Snn Raj,7147.0,4Bhk,15.35,Secondary,HNI,2024-12-31,4.525216,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.,21478.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,PROP099996,Bellary Road,Project_495,L&T Realty,5550.0,5Bhk+,10.19,Primary,NRI,2023-12-31,8.379908,7.499766,Under construction,Online,yes,8.378800,109,Underpriced for location.,18360.0
99996,PROP099997,Yelahanka,Project_496,L&T Realty,3171.0,4Bhk,12.27,Secondary,Other,2023-12-31,4.716304,6.374069,Launch,Broker,yes,7.025209,20,Great view from 15th floor.,38694.0
99997,PROP099998,Rajajinagar,Project_497,Prestige,5599.0,4BHK,13.73,Primary,Startup Founder,2023-09-30,6.193347,7.482473,Launch,NRI Desk,yes,8.984990,63,No comments,24522.0
99998,PROP099999,Indiranagar,Project_498,Snn Raj,7342.0,4bhk,10.36,Primary,NRI,2024-09-30,9.435646,6.369276,Under construction,NRI Desk,yes,7.634717,89,No comments,14111.0
99999,PROP100000,Hennur Road,Project_499,Embassy,5016.0,5Bhk+,10.42,Primary,Startup Founder,2024-09-30,5.786292,5.284026,Launch,Broker,yes,6.039943,95,No comments,20774.0

In [37]:
df["Year"]=df["Purchase_Quarter"].dt.year

In [38]:
df["Quarter"]=df["Purchase_Quarter"].dt.quarter

In [39]:
df

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,...,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments,Price_Per_Sqft,Year,Quarter
0,PROP000001,Sarjapur Road,Project_0,Rmz,4025.0,4bhk,12.75,Primary,NRI,2025-03-31,...,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!,31677.0,2025,1
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.29,Primary,Other,2024-06-30,...,7.499766,Under construction,NRI Desk,no,7.723898,106,No comments,28281.0,2024,2
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4bhk,10.52,Primary,HNI,2023-12-31,...,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.,13650.0,2023,4
3,PROP000004,Bellary Road,Project_3,Embassy,6192.0,3BHK,9.40,Primary,HNI,2024-03-31,...,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!,15181.0,2024,1
4,PROP000005,Koramangala,Project_4,Snn Raj,7147.0,4Bhk,15.35,Secondary,HNI,2024-12-31,...,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.,21478.0,2024,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,PROP099996,Bellary Road,Project_495,L&T Realty,5550.0,5Bhk+,10.19,Primary,NRI,2023-12-31,...,7.499766,Under construction,Online,yes,8.378800,109,Underpriced for location.,18360.0,2023,4
99996,PROP099997,Yelahanka,Project_496,L&T Realty,3171.0,4Bhk,12.27,Secondary,Other,2023-12-31,...,6.374069,Launch,Broker,yes,7.025209,20,Great view from 15th floor.,38694.0,2023,4
99997,PROP099998,Rajajinagar,Project_497,Prestige,5599.0,4BHK,13.73,Primary,Startup Founder,2023-09-30,...,7.482473,Launch,NRI Desk,yes,8.984990,63,No comments,24522.0,2023,3
99998,PROP099999,Indiranagar,Project_498,Snn Raj,7342.0,4bhk,10.36,Primary,NRI,2024-09-30,...,6.369276,Under construction,NRI Desk,yes,7.634717,89,No comments,14111.0,2024,3
99999,PROP100000,Hennur Road,Project_499,Embassy,5016.0,5Bhk+,10.42,Primary,Startup Founder,2024-09-30,...,5.284026,Launch,Broker,yes,6.039943,95,No comments,20774.0,2024,3

In [40]:
df["Configuration"]=df["Configuration"].str.lower()

In [41]:
df

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,...,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments,Price_Per_Sqft,Year,Quarter
0,PROP000001,Sarjapur Road,Project_0,Rmz,4025.0,4bhk,12.75,Primary,NRI,2025-03-31,...,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!,31677.0,2025,1
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3bhk,16.29,Primary,Other,2024-06-30,...,7.499766,Under construction,NRI Desk,no,7.723898,106,No comments,28281.0,2024,2
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4bhk,10.52,Primary,HNI,2023-12-31,...,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.,13650.0,2023,4
3,PROP000004,Bellary Road,Project_3,Embassy,6192.0,3bhk,9.40,Primary,HNI,2024-03-31,...,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!,15181.0,2024,1
4,PROP000005,Koramangala,Project_4,Snn Raj,7147.0,4bhk,15.35,Secondary,HNI,2024-12-31,...,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.,21478.0,2024,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,PROP099996,Bellary Road,Project_495,L&T Realty,5550.0,5bhk+,10.19,Primary,NRI,2023-12-31,...,7.499766,Under construction,Online,yes,8.378800,109,Underpriced for location.,18360.0,2023,4
99996,PROP099997,Yelahanka,Project_496,L&T Realty,3171.0,4bhk,12.27,Secondary,Other,2023-12-31,...,6.374069,Launch,Broker,yes,7.025209,20,Great view from 15th floor.,38694.0,2023,4
99997,PROP099998,Rajajinagar,Project_497,Prestige,5599.0,4bhk,13.73,Primary,Startup Founder,2023-09-30,...,7.482473,Launch,NRI Desk,yes,8.984990,63,No comments,24522.0,2023,3
99998,PROP099999,Indiranagar,Project_498,Snn Raj,7342.0,4bhk,10.36,Primary,NRI,2024-09-30,...,6.369276,Under construction,NRI Desk,yes,7.634717,89,No comments,14111.0,2024,3
99999,PROP100000,Hennur Road,Project_499,Embassy,5016.0,5bhk+,10.42,Primary,Startup Founder,2024-09-30,...,5.284026,Launch,Broker,yes,6.039943,95,No comments,20774.0,2024,3

In [42]:
df.to_csv("Luxury_Housing_Bangalore_cleaned_data.csv")